name: ❓[Automation Kit] Question
description: Ask a question about the Automation Kit
title: "[Automation Kit - QUESTION] QUESTION"
labels: ["automation-kit", "question"]
assignees: KoteshMCGit
body:
- type: textarea
  attributes:
    label: What is your question?
    description: A concise description of what you need to know. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: true
- type: dropdown
  id: component
  attributes:
    label: What component is the question related to?
    options:
      - Automation Project
      - Automation Center
      - Automation Solution Manager
      - Cloud flows
      - Power BI dashboard
      - Other
  validations:
    required: false
- type: input
  id: version
  attributes:
    label: What solution version are you using?
    placeholder: "September 2022"
  validations:
    required: false
- type: input
  id: app
  attributes:
    label: What app or flow are you having the issue with?
    placeholder: "Sync Desktop Flows"
