name: 👏 [Automation Kit] Kudos
description: Provide public feedback on the automation kit or features that have helped you
title: "[Automation Kit - Kudos] Your summary"
labels: ["automation-kit", "kudos"]
body:
- type: textarea
  attributes:
    label: What is your feedback?
    description: A concise description of how the Automation Kit or a feature of the kit have helped you
  validations:
    required: true
- type: textarea
  id: impact
  attributes:
    label: What was the impact you got?
    placeholder: "Any additional information you would like to publicly share about the impact of the Kit or feature?"
