jobs:
  - job: Key Setup
    pool:
     name: "Azure Pipelines"
     vmImage: "windows-2022"
    steps:
    - pwsh: |
        $envVariable = "SigningKey"
        $filename = "$(Build.SourcesDirectory)\powercat-automation-kit\Plugins\autocoe-plugins-master\Plugins\AutoCoEPluginKey.snk"
        if ( [System.Environment]::GetEnvironmentVariable($envVariable) -neq $NULL ) {
        $base64 = System.Environment]::GetEnvironmentVariable($envVariable)
        $bytes = [Convert]::FromBase64String($base64)
        [IO.File]::WriteAllBytes($filename, $bytes)
        }
      displayName: 'Signing Key'